version: '3.8'
services:
  api:
    image: node:16
    working_dir: /app
    volumes:
      - ./api/:/app
    command: sh -c "npm install && npx prisma migrate dev --name init && npm run start:dev"
    ports:
      - 3030:3030
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306