version: '3.8'

networks:
  api-database:
    driver: bridge

services:

  database:
    image: mysql:latest
    container_name: scardatabase
    networks:
      - api-database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  backend:
    build: ./api/
    networks:
      - api-database
    depends_on:
      - database
    ports:
      - "3030:3030"
  
  frontend:
    build: ./web/
    ports:
      - "5173:5173"
    
