import { PrismaClient } from '@prisma/client';

// initialize Prisma Client
const prisma = new PrismaClient();

async function main() {
    // base de materias e tags, para evitar erros, 
    //use apenas quando as tabelas estiverem limpas e na primeira vez que iniciar o projeto
    const materias = await prisma.types.createMany({
        data: [
            { name: "Língua Portuguesa e Literatura" },
            { name: "Inglês" },
            { name: "Espanhol" },
            { name: "Arte" },
            { name: "Educação Física" },
            { name: "Geografia" },
            { name: "História" },
            { name: "Filosofia" },
            { name: "Sociologia" },
            { name: "Matemática" },
            { name: "Física" },
            { name: "Química" },
            { name: "Biologia" },
            { name: "Informática" },
            { name: "Gestão Organizacional e Empreendedorismo" },
            { name: "Produção de texto Técnico-Científico I" },
            { name: "Produção de texto Técnico-Científico II" },
            { name: "Introdução a Química dos Alimentos" },
            { name: "Biologia aplicada a Alimentos" },
            { name: "Termologia Aplicada a Tecnologia de Alimentos" },
            { name: "Segurança do Trabalho" },
            { name: "Gestão Ambiental" },
            { name: "Introdução a Tecnologia de Alimentos" },
            { name: "Técnicas de Laboratório de Alimentos" },
            { name: "Química e Bioquímica dos Alimentos: componentes principais" },
            { name: "Química e Bioquímica dos Alimentos: componentes secundários e transformações" },
            { name: "Química e Bioquímica dos Alimentos: experimental" },
            { name: "Microbiologia dos Alimentos" },
            { name: "Biotecnologia Aplicada aos Alimentos" },
            { name: "Controle Estatístico da Qualidade" },
            { name: "Tecnologia de Frutas e Hortaliças" },
            { name: "Tecnologia de Cereais" },
            { name: "Tecnologia de Mel" },
            { name: "Higiene e Segurança Alimentar" },
            { name: "Máquinas, Equipamentos, Processos e Operações Unitárias" },
            { name: "Análise dos Alimentos" },
            { name: "Tecnologia de Leite e Derivados" },
            { name: "Tecnologia de Carnes e Pescados" },
            { name: "Embalagem, Rotulagem e Logística" },
            { name: "Análise Sensorial" },
            { name: "Filosofia, Ciência e Tecnologia" },
            { name: "Sociologia do Trabalho" },
            { name: "Qualidade de Vida e Trabalho" },
            { name: "Gestão e Empreendedorismo" },
            { name: "Instalação e Montagem de Computadores" },
            { name: "Práticas de Eletricidade" },
            { name: "Operação e Organização de Computadores" },
            { name: "Eletrônica Analógica" },
            { name: "Eletrônica Digital" },
            { name: "Eletrônica de Potência" },
            { name: "Manutenção Básica de Computadores" },
            { name: "Manutenção de Fontes de Alimentação" },
            { name: "Manutenção de Periféricos" },
            { name: "Manutenção Avançada de Computadores" },
            { name: "Infraestrutura de Redes de Computadores" },
            { name: "Sistemas Operacionais de Redes de Computadores" },
            { name: "Gestão de Serviços em Informática" },
            { name: "Gestão Organizacional" },
            { name: "Fundamentos de Lógica e Algoritmos" },
            { name: "Eletricidade Instrumental" },
            { name: "Eletrônica Analógica e Digital" },
            { name: "Organização e Manutenção de Computadores" },
            { name: "Programação Estruturada e Orientada a Objetos" },
            { name: "Programação com Acesso a Banco de Dados" },
            { name: "Projeto de Desenvolvimento de Software" },
            { name: "Autoria Web" },
            { name: "Programação para Internet" },
            { name: "Arquitetura de redes de computadores e Tecnologia de implementação de redes" },
            { name: "Fundamentos de sistemas operacionais e Sistemas operacionais de redes" },
            { name: "Língua Portuguesa" },
            { name: "Leitura e Escrita de Textos Acadêmicos e de Divulgação Científica" },
            { name: "Matemática Básica" },
            { name: "Psicologia da Aprendizagem" },
            { name: "Didática" },
            { name: "Organização e Gestão da Educação Brasileira" },
            { name: "Mídias Educacionais" },
            { name: "Educação Inclusiva" },
            { name: "LIBRAS" },
            { name: "Fundamentos da Educação I" },
            { name: "Fundamentos da Educação II" },
            { name: "Epistemologia da Ciência" },
            { name: "Metodologia do Trabalho Científico" },
            { name: "Metodologia do Ensino de Química I" },
            { name: "Metodologia do Ensino de Química II" },
            { name: "Química Geral I" },
            { name: "Química Geral II" },
            { name: "Química Experimental I" },
            { name: "Química Experimental II" },
            { name: "Química Inorgânica" },
            { name: "Química Inorgânica de Coordenação" },
            { name: "Físico-Química Teórica e Experimental I" },
            { name: "Físico-Química Teórica e Experimental II" },
            { name: "Físico Química Teórica e Experimental III" },
            { name: "Química Orgânica Fundamental" },
            { name: "Mecanismo de Reações Orgânicas" },
            { name: "Química Analítica Qualitativa" },
            { name: "Química Analítica Quantitativa" },
            { name: "Química dos Elementos" },
            { name: "Química Inorgânica Experimental" },
            { name: "Cálculo Diferencial e Integral I" },
            { name: "Cálculo Diferencial e Integral II" },
            { name: "Física I" },
            { name: "Física II" },
            { name: "Bioquímica" },
            { name: "Fundamentos da Pesquisa em Educação Química" },
            { name: "Biologia para o Ensino de Ciências" },
            { name: "Química Orgânica Experimental" },
            { name: "Química Ambiental" },
            { name: "Estatística aplicada à Química" },
            { name: "Concepções e Práticas da Educação de Jovens e Adultos" },
            { name: "Concepções e Práticas de Avaliação da Aprendizagem" },
            { name: "Educação para a Diversidade" },
            { name: "Educação para o Desenvolvimento Sustentável" },
            { name: "Ética da Docência" },
            { name: "Fundamentos da Educação Profissional e Tecnológica" },
            { name: "Filosofia da Técnica e da Tecnologia" },
            { name: "Formação de Professores e Trabalho Docente" },
            { name: "Fundamentos da Educação a Distância" },
            { name: "LIBRAS II" },
            { name: "Teoria e Organização curricular" },
            { name: "Educação em Direitos Humanos" },
            { name: "Análises de Águas e Efluentes I" },
            { name: "Análises de Águas e Efluentes II" },
            { name: "Espectroscopia dos Compostos de Coordenação" },
            { name: "Fundamentos da Espectroscopia de Absorção Molecular no UV/Vis" },
            { name: "Métodos Cromatográficos" },
            { name: "Métodos Instrumentais de Caracterização de Compostos Orgânicos" },
            { name: "Mineralogia" },
            { name: "Química dos Biocombustíveis" },
            { name: "Química de Produtos Naturais" },
            { name: "Tratamento de Água e Efluentes" },
            { name: "Física para o Ensino de Ciências" },
            { name: "Língua Inglesa" },
            { name: "Informática Básica" },
            { name: "Cálculo Diferencial e Integral" },
            { name: "Estatística" },
            { name: "Ética e Cidadania" },
            { name: "Química Geral" },
            { name: "Química Orgânica" },
            { name: "Físico-Química" },
            { name: "Química Analítica" },
            { name: "Desenho Técnico Auxiliado por Computador" },
            { name: "Microbiologia de Alimentos I" },
            { name: "Microbiologia de Alimentos II" },
            { name: "Princípios da Conservação de Alimentos" },
            { name: "Química dos Alimentos" },
            { name: "Matérias-Primas Agropecuárias" },
            { name: "Gestão da Qualidade e Legislação de Alimentos" },
            { name: "Bioquímica dos Alimentos" },
            { name: "Termodinâmica Aplicada e Fenômenos de Transportes" },
            { name: "Tecnologia de Laticínios" },
            { name: "Biotecnologia de Alimentos" },
            { name: "Tecnologia de Pescado" },
            { name: "Tecnologia de Carnes" },
            { name: "Armazenamento e Logística" },
            { name: "Operações Unitárias Aplicadas à Alimentos" },
            { name: "Higiene da Indústria de Alimentos" },
            { name: "Instrumentação e Instalações Industriais" },
            { name: "Embalagens" },
            { name: "Língua Espanhola" },
            { name: "Análise de Água" },
            { name: "Tratamento de Águas e Efluentes na Indústria Alimentícia" },
            { name: "Tecnologia de Bebidas Alcóolicas" },
            { name: "Tecnologia de Óleos e Gorduras" },
            { name: "Tecnologia de Amido, Farinhas e Derivados" },
            { name: "Pesquisa e Desenvolvimento de Novos Produtos" },
            { name: "Tecnologia Pós-Colheita de Frutas e Hortaliças" },
            { name: "Sociologia e Tecnologia" },
            { name: "Empreendedorismo" },
            { name: "Introdução à Lógica e Programação" },
            { name: "Fundamentos de Sistemas Operacionais" },
            { name: "Padrões Web" },
            { name: "Sistemas Operacionais Abertos" },
            { name: "Bancos de Dados" },
            { name: "Programação Orientada a Objetos" },
            { name: "Desenvolvimento Web Front-end" },
            { name: "Redes de Computadores" },
            { name: "Estruturas de Dados" },
            { name: "Programação em Bancos de Dados" },
            { name: "Análise e Projeto de Sistemas Web" },
            { name: "Desenvolvimento Web Back-end" },
            { name: "Sistemas Digitais" },
            { name: "Desenvolvimento de Sistemas Corporativos" },
            { name: "Processo de Desenvolvimento e Implantação de Sistemas Web" },
            { name: "Sistemas Distribuídos" },
            { name: "Teste de Software" },
            { name: "Programação para Internet das Coisas" },
            { name: "Gerência e Conf. de Serviços para a Internet" },
            { name: "Desenvolvimento para Dispositivos Móveis" },
            { name: "Técnicas de Análise de Dados" },
            { name: "Segurança e Preservação de Dados" },
            { name: "Desenvolvimento Web para a Nuvem" },
            { name: "Introdução à Informática" },
            { name: "Educação Ambiental" },
            { name: "Psicologia das Relações de Trabalho" },
            { name: "Legislação Aplicada à Tecnologia da Informação" },
            { name: "Web Design" },
            { name: "Redes Multimídia" },
            { name: "Sistemas Operacionais Proprietários" },
            { name: "Tecnologias de Banco de Dados" },
            { name: "Desenvolvimento com Ferramentas RAD" },
            { name: "Sistemas Embarcados" },
            { name: "Governança de TI" },
            { name: "Qualidade de Software" },
            { name: "Gerenciamento de Projeto de Software" },
            { name: "Gestão de Pessoas" },
            { name: "Computação Forense" },
            { name: "Tópicos Avançados em Sistemas para Internet" },
        ]
    });

    console.log(materias)

    const tags = await prisma.tags.createMany({
        data: [
            { name: "Língua Portuguesa e Literatura", typeId: 1 },
            { name: "Inglês", typeId: 2 },
            { name: "Espanhol", typeId: 3 },
            { name: "Arte", typeId: 4 },
            { name: "Educação Física", typeId: 5 },
            { name: "Geografia", typeId: 6 },
            { name: "História", typeId: 7 },
            { name: "Filosofia", typeId: 8 },
            { name: "Sociologia", typeId: 9 },
            { name: "Matemática", typeId: 10 },
            { name: "Física", typeId: 11 },
            { name: "Química", typeId: 12 },
            { name: "Biologia", typeId: 13 },
            { name: "Informática", typeId: 14 },
            { name: "Gestão Organizacional e Empreendedorismo", typeId: 15 },
            { name: "Produção de texto Técnico-Científico I", typeId: 16 },
            { name: "Produção de texto Técnico-Científico II", typeId: 17 },
            { name: "Introdução a Química dos Alimentos", typeId: 18 },
            { name: "Biologia aplicada a Alimentos", typeId: 19 },
            { name: "Termologia Aplicada a Tecnologia de Alimentos", typeId: 20 },
            { name: "Segurança do Trabalho", typeId: 21 },
            { name: "Gestão Ambiental", typeId: 22 },
            { name: "Introdução a Tecnologia de Alimentos", typeId: 23 },
            { name: "Técnicas de Laboratório de Alimentos", typeId: 24 },
            { name: "Química e Bioquímica dos Alimentos: componentes principais", typeId: 25 },
            { name: "Química e Bioquímica dos Alimentos: componentes secundários e transformações", typeId: 26 },
            { name: "Química e Bioquímica dos Alimentos: experimental", typeId: 27 },
            { name: "Microbiologia dos Alimentos", typeId: 28 },
            { name: "Biotecnologia Aplicada aos Alimentos", typeId: 29 },
            { name: "Controle Estatístico da Qualidade", typeId: 30 },
            { name: "Tecnologia de Frutas e Hortaliças", typeId: 31 },
            { name: "Tecnologia de Cereais", typeId: 32 },
            { name: "Tecnologia de Mel", typeId: 33 },
            { name: "Higiene e Segurança Alimentar", typeId: 34 },
            { name: "Máquinas, Equipamentos, Processos e Operações Unitárias", typeId: 35 },
            { name: "Análise dos Alimentos", typeId: 36 },
            { name: "Tecnologia de Leite e Derivados", typeId: 37 },
            { name: "Tecnologia de Carnes e Pescados", typeId: 38 },
            { name: "Embalagem, Rotulagem e Logística", typeId: 39 },
            { name: "Análise Sensorial", typeId: 40 },
            { name: "Filosofia, Ciência e Tecnologia", typeId: 41 },
            { name: "Sociologia do Trabalho", typeId: 42 },
            { name: "Qualidade de Vida e Trabalho", typeId: 43 },
            { name: "Gestão e Empreendedorismo", typeId: 44 },
            { name: "Instalação e Montagem de Computadores", typeId: 45 },
            { name: "Práticas de Eletricidade", typeId: 46 },
            { name: "Operação e Organização de Computadores", typeId: 47 },
            { name: "Eletrônica Analógica", typeId: 48 },
            { name: "Eletrônica Digital", typeId: 49 },
            { name: "Eletrônica de Potência", typeId: 50 },
            { name: "Manutenção Básica de Computadores", typeId: 51 },
            { name: "Manutenção de Fontes de Alimentação", typeId: 52 },
            { name: "Manutenção de Periféricos", typeId: 53 },
            { name: "Manutenção Avançada de Computadores", typeId: 54 },
            { name: "Infraestrutura de Redes de Computadores", typeId: 55 },
            { name: "Sistemas Operacionais de Redes de Computadores", typeId: 56 },
            { name: "Gestão de Serviços em Informática", typeId: 57 },
            { name: "Gestão Organizacional", typeId: 58 },
            { name: "Fundamentos de Lógica e Algoritmos", typeId: 59 },
            { name: "Eletricidade Instrumental", typeId: 60 },
            { name: "Eletrônica Analógica e Digital", typeId: 61 },
            { name: "Organização e Manutenção de Computadores", typeId: 62 },
            { name: "Programação Estruturada e Orientada a Objetos", typeId: 63 },
            { name: "Programação com Acesso a Banco de Dados", typeId: 64 },
            { name: "Projeto de Desenvolvimento de Software", typeId: 65 },
            { name: "Autoria Web", typeId: 66 },
            { name: "Programação para Internet", typeId: 67 },
            { name: "Arquitetura de redes de computadores e Tecnologia de implementação de redes", typeId: 68 },
            { name: "Fundamentos de sistemas operacionais e Sistemas operacionais de redes", typeId: 69 },
            { name: "Língua Portuguesa", typeId: 70 },
            { name: "Leitura e Escrita de Textos Acadêmicos e de Divulgação Científica", typeId: 71 },
            { name: "Matemática Básica", typeId: 72 },
            { name: "Psicologia da Aprendizagem", typeId: 73 },
            { name: "Didática", typeId: 74 },
            { name: "Organização e Gestão da Educação Brasileira", typeId: 75 },
            { name: "Mídias Educacionais", typeId: 76 },
            { name: "Educação Inclusiva", typeId: 77 },
            { name: "LIBRAS", typeId: 78 },
            { name: "Fundamentos da Educação I", typeId: 79 },
            { name: "Fundamentos da Educação II", typeId: 80 },
            { name: "Epistemologia da Ciência", typeId: 81 },
            { name: "Metodologia do Trabalho Científico", typeId: 82 },
            { name: "Metodologia do Ensino de Química I", typeId: 83 },
            { name: "Metodologia do Ensino de Química II", typeId: 84 },
            { name: "Química Geral I", typeId: 85 },
            { name: "Química Geral II", typeId: 86 },
            { name: "Química Experimental I", typeId: 87 },
            { name: "Química Experimental II", typeId: 88 },
            { name: "Química Inorgânica", typeId: 89 },
            { name: "Química Inorgânica de Coordenação", typeId: 90 },
            { name: "Físico-Química Teórica e Experimental I", typeId: 91 },
            { name: "Físico-Química Teórica e Experimental II", typeId: 92 },
            { name: "Físico Química Teórica e Experimental III", typeId: 93 },
            { name: "Química Orgânica Fundamental", typeId: 94 },
            { name: "Mecanismo de Reações Orgânicas", typeId: 95 },
            { name: "Química Analítica Qualitativa", typeId: 96 },
            { name: "Química Analítica Quantitativa", typeId: 97 },
            { name: "Química dos Elementos", typeId: 98 },
            { name: "Química Inorgânica Experimental", typeId: 99 },
            { name: "Cálculo Diferencial e Integral I", typeId: 100 },
            { name: "Cálculo Diferencial e Integral II", typeId: 101 },
            { name: "Física I", typeId: 102 },
            { name: "Física II", typeId: 103 },
            { name: "Bioquímica", typeId: 104 },
            { name: "Fundamentos da Pesquisa em Educação Química", typeId: 105 },
            { name: "Biologia para o Ensino de Ciências", typeId: 106 },
            { name: "Química Orgânica Experimental", typeId: 107 },
            { name: "Química Ambiental", typeId: 108 },
            { name: "Estatística aplicada à Química", typeId: 109 },
            { name: "Concepções e Práticas da Educação de Jovens e Adultos", typeId: 110 },
            { name: "Concepções e Práticas de Avaliação da Aprendizagem", typeId: 111 },
            { name: "Educação para a Diversidade", typeId: 112 },
            { name: "Educação para o Desenvolvimento Sustentável", typeId: 113 },
            { name: "Ética da Docência", typeId: 114 },
            { name: "Fundamentos da Educação Profissional e Tecnológica", typeId: 115 },
            { name: "Filosofia da Técnica e da Tecnologia", typeId: 116 },
            { name: "Formação de Professores e Trabalho Docente", typeId: 117 },
            { name: "Fundamentos da Educação a Distância", typeId: 118 },
            { name: "LIBRAS II", typeId: 119 },
            { name: "Teoria e Organização curricular", typeId: 120 },
            { name: "Educação em Direitos Humanos", typeId: 121 },
            { name: "Análises de Águas e Efluentes I", typeId: 122 },
            { name: "Análises de Águas e Efluentes II", typeId: 123 },
            { name: "Espectroscopia dos Compostos de Coordenação", typeId: 124 },
            { name: "Fundamentos da Espectroscopia de Absorção Molecular no UV/Vis", typeId: 125 },
            { name: "Métodos Cromatográficos", typeId: 126 },
            { name: "Métodos Instrumentais de Caracterização de Compostos Orgânicos", typeId: 127 },
            { name: "Mineralogia", typeId: 128 },
            { name: "Química dos Biocombustíveis", typeId: 129 },
            { name: "Química de Produtos Naturais", typeId: 130 },
            { name: "Tratamento de Água e Efluentes", typeId: 131 },
            { name: "Física para o Ensino de Ciências", typeId: 132 },
            { name: "Língua Inglesa", typeId: 133 },
            { name: "Informática Básica", typeId: 134 },
            { name: "Cálculo Diferencial e Integral", typeId: 135 },
            { name: "Estatística", typeId: 136 },
            { name: "Ética e Cidadania", typeId: 137 },
            { name: "Química Geral", typeId: 138 },
            { name: "Química Orgânica", typeId: 139 },
            { name: "Físico-Química", typeId: 140 },
            { name: "Química Analítica", typeId: 141 },
            { name: "Desenho Técnico Auxiliado por Computador", typeId: 142 },
            { name: "Microbiologia de Alimentos I", typeId: 143 },
            { name: "Microbiologia de Alimentos II", typeId: 144 },
            { name: "Princípios da Conservação de Alimentos", typeId: 145 },
            { name: "Química dos Alimentos", typeId: 146 },
            { name: "Matérias-Primas Agropecuárias", typeId: 147 },
            { name: "Gestão da Qualidade e Legislação de Alimentos", typeId: 148 },
            { name: "Bioquímica dos Alimentos", typeId: 149 },
            { name: "Termodinâmica Aplicada e Fenômenos de Transportes", typeId: 150 },
            { name: "Tecnologia de Laticínios", typeId: 151 },
            { name: "Biotecnologia de Alimentos", typeId: 152 },
            { name: "Tecnologia de Pescado", typeId: 153 },
            { name: "Tecnologia de Carnes", typeId: 154 },
            { name: "Armazenamento e Logística", typeId: 155 },
            { name: "Operações Unitárias Aplicadas à Alimentos", typeId: 156 },
            { name: "Higiene da Indústria de Alimentos", typeId: 157 },
            { name: "Instrumentação e Instalações Industriais", typeId: 158 },
            { name: "Embalagens", typeId: 159 },
            { name: "Língua Espanhola", typeId: 160 },
            { name: "Análise de Água", typeId: 161 },
            { name: "Tratamento de Águas e Efluentes na Indústria Alimentícia", typeId: 162 },
            { name: "Tecnologia de Bebidas Alcóolicas", typeId: 163 },
            { name: "Tecnologia de Óleos e Gorduras", typeId: 164 },
            { name: "Tecnologia de Amido, Farinhas e Derivados", typeId: 165 },
            { name: "Pesquisa e Desenvolvimento de Novos Produtos", typeId: 166 },
            { name: "Tecnologia Pós-Colheita de Frutas e Hortaliças", typeId: 167 },
            { name: "Sociologia e Tecnologia", typeId: 168 },
            { name: "Empreendedorismo", typeId: 169 },
            { name: "Introdução à Lógica e Programação", typeId: 170 },
            { name: "Fundamentos de Sistemas Operacionais", typeId: 171 },
            { name: "Padrões Web", typeId: 172 },
            { name: "Sistemas Operacionais Abertos", typeId: 173 },
            { name: "Bancos de Dados", typeId: 174 },
            { name: "Programação Orientada a Objetos", typeId: 175 },
            { name: "Desenvolvimento Web Front-end", typeId: 176 },
            { name: "Redes de Computadores", typeId: 177 },
            { name: "Estruturas de Dados", typeId: 178 },
            { name: "Programação em Bancos de Dados", typeId: 179 },
            { name: "Análise e Projeto de Sistemas Web", typeId: 180 },
            { name: "Desenvolvimento Web Back-end", typeId: 181 },
            { name: "Sistemas Digitais", typeId: 182 },
            { name: "Desenvolvimento de Sistemas Corporativos", typeId: 183 },
            { name: "Processo de Desenvolvimento e Implantação de Sistemas Web", typeId: 184 },
            { name: "Sistemas Distribuídos", typeId: 185 },
            { name: "Teste de Software", typeId: 186 },
            { name: "Programação para Internet das Coisas", typeId: 187 },
            { name: "Gerência e Conf. de Serviços para a Internet", typeId: 188 },
            { name: "Desenvolvimento para Dispositivos Móveis", typeId: 189 },
            { name: "Técnicas de Análise de Dados", typeId: 190 },
            { name: "Segurança e Preservação de Dados", typeId: 191 },
            { name: "Desenvolvimento Web para a Nuvem", typeId: 192 },
            { name: "Introdução à Informática", typeId: 193 },
            { name: "Educação Ambiental", typeId: 194 },
            { name: "Psicologia das Relações de Trabalho", typeId: 195 },
            { name: "Legislação Aplicada à Tecnologia da Informação", typeId: 196 },
            { name: "Web Design", typeId: 197 },
            { name: "Redes Multimídia", typeId: 198 },
            { name: "Sistemas Operacionais Proprietários", typeId: 199 },
            { name: "Tecnologias de Banco de Dados", typeId: 200 },
            { name: "Desenvolvimento com Ferramentas RAD", typeId: 201 },
            { name: "Sistemas Embarcados", typeId: 202 },
            { name: "Governança de TI", typeId: 203 },
            { name: "Qualidade de Software", typeId: 204 },
            { name: "Gerenciamento de Projeto de Software", typeId: 205 },
            { name: "Gestão de Pessoas", typeId: 206 },
            { name: "Computação Forense", typeId: 207 },
            { name: "Tópicos Avançados em Sistemas para Internet", typeId: 208 },
        ]
    });
    console.log(tags)
}

// execute the main function
main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        // close Prisma Client at the end
        await prisma.$disconnect();
    });